### ISSUE TITLE
GIDS数据集预训练模型

### ISSUE THREAD

**Issue by ZYanXiang** [antct/cil#2]
请问可否提供一下GIDS数据集下CIL模型的PR曲线获取预训练模型？

**Comment by antct** [comment]
hello，GIDS数据集我看了看之前的记录，只存了运行的结果，没有保存相应的文件。sorry~

**Comment by ZYanXiang** [comment]
好的，谢谢回复！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antct/cil"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月16日(星期三) 中午1:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [antct/cil] GIDS数据集预训练模型 (Issue #2)





 
hello，GIDS数据集我看了看之前的记录，只存了运行的结果，没有保存相应的文件。sorry~
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
