### ISSUE TITLE
KBP数据集预处理

### ISSUE THREAD

**Issue by Emma1066** [antct/cil#5]
您好，感谢您分享您的源码。

关于KBP数据预处理我有以下2个问题想向您请教：
1. KBP未处理的数据文件中，“brown”文件的含义和作用是什么？
2. 在readme中给出的处理好的KBP样例中，实体id样式为"1-a"、"1-b"这种（如下所示），请问您是如何定义的呢？我猜测是跟未处理的源格式有一定联系，不知是否正确。

```
kbp_train.txt kbp_dev.txt kbp_test.txt
{"text": "An American Civil rights activist , Martin Luther King , Jr. was assassinated in 1968 by James Earl Ray in Memphis , Tennessee .", 
"relation": "no_relation",
 "h": {"id": "1-a", "name": "American Civil", "pos": [3, 17]}, 
"t": {"id": "1-b", "name": "James Earl Ray", "pos": [89, 103]}}
```

感谢您的解答！

**Comment by antct** [comment]
1. brown具体含义我也不太记得了，似乎是没啥用。
2. 因为kbp是一个sentence-level的数据集，所以我这边直接用不同的idx来区分。相当于给每一个句子分配一个不同的idx，两个实体分别为idx-a和idx-b，这样就不会有任何两个句子构建成包，即sentence-level。

**Comment by Emma1066** [comment]
谢谢您的回复！

KBP原始数据中，一个句子会存在多个关系，即多个不同的(h, t, r)组合，例如下面例子中，该条句子对应有5个不同的关系。那么就给这5个关系分别分配不同的句子id，从而构建出5个sample，请问这样理解对吗（即使他们对应的句子实际上是同一个）？

```
{
  "sentText": "Mohammed Oudeh, a former math teacher who became the mastermind of the deadly attack on Israeli athletes at the 1972 Munich Olympics, died Friday in Damascus..",
  "articleId": "NYT-ENG-20100704.0043",
  "relationMentions": [
    {"em1Text": "Mohammed Oudeh", "em2Text": "Damascus", "label": "per:country_of_death"},
    {"em1Text": "Munich", "em2Text": "Damascus", "label": "None"},
    {"em1Text": "Damascus", "em2Text": "Munich", "label": "None"},
    {"em1Text": "Mohammed Oudeh", "em2Text": "Munich", "label": "None"},
    {"em1Text": "Munich", "em2Text": "Mohammed Oudeh", "label": "None"}
  ],
  "entityMentions": [
    {"start": 0, "label": "/person", "text": "Mohammed Oudeh"},
    {"start": 1, "label": "/art/film,/art", "text": "Munich"},
    {"start": 2, "label": "/location/city,/location", "text": "Damascus"}
  ],
  "sentId": "417"
}
```

**Comment by antct** [comment]
是滴

**Comment by antct** [comment]
> 谢谢您的回复！
> 
> KBP原始数据中，一个句子会存在多个关系，即多个不同的(h, t, r)组合，例如下面例子中，该条句子对应有5个不同的关系。那么就给这5个关系分别分配不同的句子id，从而构建出5个sample，请问这样理解对吗（即使他们对应的句子实际上是同一个）？
> 
> ```
> {
>   "sentText": "Mohammed Oudeh, a former math teacher who became the mastermind of the deadly attack on Israeli athletes at the 1972 Munich Olympics, died Friday in Damascus..",
>   "articleId": "NYT-ENG-20100704.0043",
>   "relationMentions": [
>     {"em1Text": "Mohammed Oudeh", "em2Text": "Damascus", "label": "per:country_of_death"},
>     {"em1Text": "Munich", "em2Text": "Damascus", "label": "None"},
>     {"em1Text": "Damascus", "em2Text": "Munich", "label": "None"},
>     {"em1Text": "Mohammed Oudeh", "em2Text": "Munich", "label": "None"},
>     {"em1Text": "Munich", "em2Text": "Mohammed Oudeh", "label": "None"}
>   ],
>   "entityMentions": [
>     {"start": 0, "label": "/person", "text": "Mohammed Oudeh"},
>     {"start": 1, "label": "/art/film,/art", "text": "Munich"},
>     {"start": 2, "label": "/location/city,/location", "text": "Damascus"}
>   ],
>   "sentId": "417"
> }
> ```

是滴
